### ISSUE TITLE
A better UI Signup page

### ISSUE THREAD

**Issue by rajritu833** [rajritu833/Types-of-HTML-form#2]
Hey! I want a better UI of Signup Page... which includes standard background image, text, and a well sorted form. If you can do this please pull a request.

**Comment by ajay007-E** [comment]
Can i do it..???

**Comment by agaveyonatan** [comment]
sure @rajritu833 i can help you

**Comment by rajritu833** [comment]
i have added your both codes @ajay007-E and @agaveyonatan . Thank you for the contribution
